# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fcc0b9ed917f7b110c9129a4c516297df7141093c9929a84beec3b2c072525bd7820ed976b1b7bb146ea9948647bdb4bd625a33767b8e567c3d1392d0d13ef1

test:
  secret_key_base: 0a3b5b441578da1ad9c3e57196a69455d8de5c65133e75fa71674f49aa3784ab2812d6bae1eb67f47c4e4d7db3794cfcd8fe1583a8062d1dc57954f56575ebca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
